
### Raw Events Samples

In this section, you will find examples of raw logs as generated natively by the source. These examples are provided to help integrators understand the data format before ingestion into Sekoia.io. It is crucial for setting up the correct parsing stages and ensuring that all relevant information is captured.


=== "accepted_google_authenticator"

    ```
	 Accepted google_authenticator for root
    ```



=== "accepted_gssapi-with-mic"

    ```
	 Accepted gssapi-with-mic for ubuntu from 1.2.3.4 port 51826 ssh2
    ```



=== "accepted_password"

    ```
	 Accepted password for ubuntu from 1.2.3.4 port 51826 ssh2
    ```



=== "accepted_publickey"

    ```
	 Accepted publickey for ubuntu from 1.2.3.4 port 51826 ssh2: RSA SHA256:AbpHGcgLb+kRsJGnwFEktk7uzpZOCcBY74+YBdrKVGs=
    ```



=== "accepted_publickey_2"

    ```
	 Accepted publickey for jdoe@example.local from 1.2.3.4 port 59294 ssh2: ED25519 SHA256:AbpHGcgLb+kRsJGnwFEktk7uzpZOCcBY74+YBdrKVGs=
    ```



=== "authentication_attempts_exceeded"

    ```
	 error: maximum authentication attempts exceeded for invalid user support from ssh.example.org port 51219 ssh2 [preauth]
    ```



=== "authentication_attempts_exceeded_2"

    ```
	 error: maximum authentication attempts exceeded for root from 1.2.3.4 port 63758 ssh2 [preauth]
    ```



=== "authentication_too_many_failures"

    ```
	 Disconnecting invalid user support 1.2.3.4 port 51219: Too many authentication failures [preauth]
    ```



=== "bad_protocol"

    ```
	 Bad protocol version identification '\003' from 1.2.3.4 port 407
    ```



=== "connection_closed"

    ```
	 Connection closed by 1.2.3.4 port 51488 [preauth]
    ```



=== "connection_closed_authenticating_user"

    ```
	 Connection closed by authenticating user backup 1.2.3.4 port 49424 [preauth]
    ```



=== "connection_closed_illegal_user"

    ```
	 Connection closed by illegal user default 1.2.3.4 port 49424 [preauth]
    ```



=== "connection_closed_invalid_user"

    ```
	 Connection closed by invalid user pi 1.2.3.4 port 42608 [preauth]
    ```



=== "connection_closed_invalid_without_user"

    ```
	 Connection closed by invalid user 1.2.3.4 port 36797 [preauth]
    ```



=== "connection_corrupted"

    ```
	 ssh_dispatch_run_fatal: Connection from 1.2.3.4 port 49065: Connection corrupted [preauth]
    ```



=== "connection_reset"

    ```
	 Connection reset by 1.2.3.4 port 45611 [preauth]
    ```



=== "disconnect_with_header"

    ```
	Mar 11 11:26:54 foobar sshd[3296336]: Received disconnect from 1.1.1.1 port 33980:11: Bye Bye
    ```



=== "disconnected"

    ```
	 Disconnected from 1.2.3.4 port 39906 [preauth]
    ```



=== "disconnected_authenticating_user"

    ```
	 Disconnected from authenticating user backup 1.2.3.4 port 49424 [preauth]
    ```



=== "disconnected_illegal_user"

    ```
	 Disconnected from illegal user default 1.2.3.4 port 48792 [preauth]
    ```



=== "disconnected_user"

    ```
	 Disconnected from user ubuntu 1.2.3.4 port 44708
    ```



=== "disconnected_user_with_domain"

    ```
	 Disconnected from user jdoe@lexample.local 1.2.3.4 port 33480
    ```



=== "failed_none"

    ```
	Failed none for invalid user guest from 1.2.3.4 port 15806 ssh2
    ```



=== "failed_packet"

    ```
	fatal: userauth_finish: send failure packet: Broken pipe [preauth]
    ```



=== "failed_password"

    ```
	 Failed password for backup from 1.2.3.4 port 60150 ssh2
    ```



=== "failed_password_redacted"

    ```
	 Failed password for invalid user ***** from 1.2.3.4 port 51894 ssh2
    ```



=== "failure_timeout"

    ```
	fatal: Timeout before authentication for 1.2.3.4 port 52076
    ```



=== "invalid_user"

    ```
	 Invalid user jdoe from ssh.example.org port 48792
    ```



=== "invalid_user2"

    ```
	 input_userauth_request: invalid user jdoe [preauth]
    ```



=== "invalid_user_redacted"

    ```
	 Invalid user ***** from 1.2.3.4 port 51894
    ```



=== "kex_exchange_identification"

    ```
	 error: kex_exchange_identification: Connection closed by remote host
    ```



=== "not_receive_identification"

    ```
	 Did not receive identification string from 1.2.3.4 port 50622
    ```



=== "pam_authentication_failure"

    ```
	 pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=1.2.3.4
    ```



=== "pam_check_pass"

    ```
	 pam_unix(sshd:auth): check pass; user unknown
    ```



=== "pam_more_auth_failure"

    ```
	PAM 2 more authentication failures; logname= uid=0 euid=0 tty=ssh ruser= rhost=1.2.3.4  user=root
    ```



=== "pam_service_ignoring_max_retries"

    ```
	PAM service(sshd) ignoring max retries; 6 > 3
    ```



=== "pam_session_closed"

    ```
	 pam_unix(sshd:session): session closed for user ubuntu
    ```



=== "pam_session_opened"

    ```
	 pam_unix(sshd:session): session opened for user ubuntu by (uid=0)
    ```



=== "pam_session_opened_2"

    ```
	 pam_unix(sshd:session): session opened for user jdoe(uid=10357) by (uid=0)
    ```



=== "pam_winbind_granted_access"

    ```
	 pam_winbind(sshd:account): user 'jdoe@example.local' granted access
    ```



=== "received_disconnect_bye_bye"

    ```
	 Received disconnect from 1.2.3.4 port 39906:11: Bye Bye [preauth]
    ```



=== "received_disconnect_empty_message"

    ```
	 Received disconnect from 1.2.3.4 port 16899:11:  [preauth]
    ```



=== "received_disconnect_thank_you"

    ```
	 Received disconnect from 1.2.3.4 port 36958:11: Normal Shutdown, Thank you for playing [preauth]
    ```



=== "received_disconnect_user"

    ```
	 Received disconnect from 1.2.3.4 port 44708:11: disconnected by user
    ```



=== "unable_to_negociate"

    ```
	 Unable to negotiate with 1.2.3.4 port 27824: no matching cipher found. Their offer: aes256-cbc,rijndael-cbc@lysator.liu.se,aes192-cbc,aes128-cbc,arcfour128,arcfour,3des-cbc,none [preauth]
    ```



=== "user_not_allowed"

    ```
	 User root from 1.2.3.4 not allowed because not listed in AllowUsers
    ```



